### ISSUE TITLE
Clean Uninstall Process?

### ISSUE THREAD

**Issue by djolker** [mlvzk/discocss#12]
Discord continues to require hook ins from discocss even after a re-install of discord.

What's the procedure for fully removing this project and discords dependency on it?

**Comment by hikaruisasleep** [comment]
only doing `rm -r ~/.config/discord/*/modules/discord_desktop_core` throws another error. i also did `rm -r ~/.config/discord/*/modules/installed.json` and only then Discord redownloaded the original asar file sucessfully. i think it's because `discord_desktop_core` is still installed and tries to load it.

**Comment by joshmedeski** [comment]
For macOS, I wiped `~/Library/Application Support/discord` to reset everything and remove discocss. But you'll have to log in again.
